/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited.
// Normally generated by Next.js; committed here so `tsc --noEmit` works in CI.
