# generated by datamodel-codegen:
#   filename:  claim.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class ClaimType(Enum):
    EMPIRICAL = "empirical"
    LEGAL = "legal"
    DEFINITIONAL = "definitional"
    PREDICTIVE = "predictive"
    NORMATIVE = "normative"


class Claim(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(description="Stable identifier of this claim.")]
    text: Annotated[str, Field(description="Normalized claim statement.")]
    claim_type: ClaimType
    actors: Annotated[
        list[str] | None, Field(description="Entities asserted to act.")
    ] = []
    targets: Annotated[
        list[str] | None, Field(description="Entities asserted to be acted upon.")
    ] = []
    events: Annotated[
        list[str] | None, Field(description="Events referenced by the claim.")
    ] = []
    locations: list[str] | None = []
    dates: Annotated[
        list[str] | None,
        Field(
            description="Dates/intervals referenced (ISO-8601 where known, else free text)."
        ),
    ] = []
    assertions: Annotated[
        list[str] | None,
        Field(description="Atomic assertions extracted from the claim text."),
    ] = []
    language: Annotated[
        str | None,
        Field(description="BCP-47 language tag of the source (e.g. ar, he, en)."),
    ] = None
    source_url: Annotated[
        str | None,
        Field(description="Origin URL, if the claim came from a web source."),
    ] = None
