# generated by datamodel-codegen:
#   filename:  verdict.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Verdict(Enum):
    VERIFIED = "Verified"
    LIKELY_TRUE = "Likely True"
    MIXED_EVIDENCE = "Mixed Evidence"
    INSUFFICIENT_EVIDENCE = "Insufficient Evidence"
    LIKELY_FALSE = "Likely False"
    FALSE = "False"


class ConfidenceBreakdown(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source_reliability: Annotated[float, Field(ge=0.0, le=1.0)]
    corroboration: Annotated[float, Field(ge=0.0, le=1.0)]
    evidence_quality: Annotated[float, Field(ge=0.0, le=1.0)]
    independence: Annotated[float, Field(ge=0.0, le=1.0)]
    freshness: Annotated[float, Field(ge=0.0, le=1.0)]
    weighted_total: Annotated[float, Field(ge=0.0, le=1.0)]


class TrustResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    score: Annotated[float, Field(ge=0.0, le=1.0)]
    verdict: Verdict
    breakdown: ConfidenceBreakdown
    weights_version: Annotated[
        str,
        Field(
            description="Version of the scoring config that produced this result (reproducibility)."
        ),
    ]
    relevant_count: Annotated[int, Field(ge=0)]
    supporting_count: Annotated[int, Field(ge=0)]
    contradicting_count: Annotated[int, Field(ge=0)]
    net_support: Annotated[
        float,
        Field(
            description="(support_mass - contradict_mass) / total_mass.",
            ge=-1.0,
            le=1.0,
        ),
    ]
    conflict_ratio: Annotated[
        float, Field(description="minority_mass / total_mass.", ge=0.0, le=0.5)
    ]
