# generated by datamodel-codegen:
#   filename:  evidence.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class EvidenceRelation(Enum):
    SUPPORTS = "supports"
    CONTRADICTS = "contradicts"
    NEUTRAL = "neutral"
    INCONCLUSIVE = "inconclusive"


class Evidence(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(description="Stable identifier of this evidence item.")]
    source_id: Annotated[
        str,
        Field(
            description="Stable id of the originating source, used for independence/corroboration."
        ),
    ]
    source_tier: Annotated[
        int,
        Field(
            description="1=primary, 2=trusted reporting, 3=context, 4=emerging.",
            ge=1,
            le=4,
        ),
    ]
    relation: EvidenceRelation
    quality: Annotated[
        float, Field(description="Strength of the supporting material.", ge=0.0, le=1.0)
    ]
    freshness: Annotated[
        float,
        Field(description="Recency, normalized; precomputed upstream.", ge=0.0, le=1.0),
    ]
